#![cfg(feature = "integration")]

use rstest::rstest;
use std::path::PathBuf;

/// Compare the decompression output of this module to the output of `funpack`
///
/// The `rice_parity` directory contains rice-compressed FITS files along with
/// their uncompressed versions generated by `funpack`. This test is to ensure
/// that the decompression logic in `fefits` produces the same pixel data as `funpack`.
#[rstest]
fn test_rice_parity(#[files("tests/fixtures/rice_parity/*.fits")] path: PathBuf) {
    use fefits::fits::Fits;

    // Open the funpacked image and read the image data
    let mut fits = Fits::open(&path).expect("failed to open uncompressed file");
    let Some(hdu_index) = fits.find_image().expect("Error scanning HDUs") else {
        panic!("No image HDU found in uncompressed file");
    };
    let uncompressed_pixels = fits
        .read_image(hdu_index)
        .expect("Failed to read uncompressed image")
        .into_f64();

    // Open the compressed file and read the image data
    let compressed_path = path.with_extension("fits.fz");
    let mut fits = Fits::open(&compressed_path).expect("failed to open compressed file");
    let Some(hdu_index) = fits.find_image().expect("Error scanning HDUs") else {
        panic!("No image HDU found in compressed file");
    };
    let decompressed_pixels = fits
        .read_image(hdu_index)
        .expect("Failed to read compressed image")
        .into_f64();

    // Compare the two pixel arrays
    assert_eq!(
        decompressed_pixels.len(),
        uncompressed_pixels.len(),
        "pixel count mismatch"
    );
    for (i, (decomp, uncomp)) in decompressed_pixels
        .iter()
        .zip(uncompressed_pixels.iter())
        .enumerate()
    {
        assert_eq!(decomp, uncomp, "pixel mismatch at index {i}");
    }
}
